package hearthlandsoptimizer;

import java.util.HashMap;

/**
 * Holds a multiset of {@link Building} where each element can appear multiple
 * times, including as fractions of an element.
 * 
 * @param <Building> the {@code Building}.
 * @param <Float> the amount of {@code Building}.
 * @author Amélia @SlayZeKyriarchy
 *
 */
public class BuildingMultiset extends HashMap<Building, Float>
        implements Multiset<Building> {
    
    /**
     * Generated by Eclipse.
     */
    private static final long serialVersionUID = 3901971977089369773L;
    
    /**
     * Constructs an empty {@code BuildingMultiset} with the default initial
     * capacity(16) and the default load factor (0.75).
     * 
     * {@link HashMap}
     * 
     */
    public BuildingMultiset() {
        super();
    }
    
    
//    @Override
//    public String toString() {
//        String result = "";
//        
//        return result;
//    }
}
