package hearthlandsoptimizer;

import java.util.HashMap;

/**
 * @author Amélia @SlayZeKyriarchy
 *
 */
public class ProducerMultiset extends HashMap<Producer, Integer>
        implements Multiset<Producer> {
    
    /**
     * Generated by Eclipse.
     */
    private static final long serialVersionUID = 3901971977089369773L;
    
    
}
