package hearthlandsoptimizer;

import java.util.EnumMap;

/**
 * @author Amélia @SlayZeKyriarchy
 *
 */
public class ResourceMultiset extends EnumMap<Resource, Integer>
        implements Multiset<Resource> {
    
    /**
     * Generated by Eclipse.
     */
    private static final long serialVersionUID = 7027804623365574840L;
    
    /**
     * Creates an empty resource multiset.
     */
    public ResourceMultiset() {
        super(Resource.class);
    }
    
    
    
    
}
